package com.fleetopt.app.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fleetopt.app.ui.theme.*

enum class DataProvenance(val label: String, val description: String) {
    REAL("REAL", "Direct telemetry / database record"),
    SIMULATED("SIMULATED", "Generated by simulation scenario"),
    CALCULATED("CALCULATED", "Derived from AGA-8 / real gas physics"),
    FORECAST("FORECAST", "Predicted via WMA & diurnal sales curve"),
    MANUAL("MANUAL", "Operator manual gauge telemetry input")
}

typealias Provenance = DataProvenance

@Composable
fun DataProvenanceBadge(
    provenance: DataProvenance,
    modifier: Modifier = Modifier
) {
    val (color, borderColor) = when (provenance) {
        DataProvenance.REAL -> Emerald400 to Emerald500.copy(alpha = 0.4f)
        DataProvenance.SIMULATED -> Amber400 to Amber500.copy(alpha = 0.4f)
        DataProvenance.CALCULATED -> Cyan500 to Cyan500.copy(alpha = 0.4f)
        DataProvenance.FORECAST -> Teal400 to Teal500.copy(alpha = 0.4f)
        DataProvenance.MANUAL -> Slate300 to Slate600
    }

    Box(
        modifier = modifier
            .clip(RoundedCornerShape(4.dp))
            .background(color.copy(alpha = 0.12f))
            .border(1.dp, borderColor, RoundedCornerShape(4.dp))
            .padding(horizontal = 6.dp, vertical = 2.dp)
    ) {
        Text(
            text = provenance.label,
            color = color,
            fontSize = 9.sp,
            fontWeight = FontWeight.Bold,
            letterSpacing = 0.5.sp
        )
    }
}
